#ifndef _GENERIC_PROTOCOL_CONSTANTS_HPP
#define _GENERIC_PROTOCOL_CONSTANTS_HPP

constexpr float PACKET_LOSS_PROBABILITY = 0.25;
constexpr float CORRUPTION_PROBABILITY = 0.35;
constexpr int NETWORK_LATENCY = 1000;

#endif // _GENERIC_PROTOCOL_CONSTANTS_HPP