#ifndef _GENERIC_PROTOCOL_CONSTANTS_HPP
#define _GENERIC_PROTOCOL_CONSTANTS_HPP

constexpr float PACKET_LOSS_PROBABILITY = 0.25;
constexpr int NETWORK_LATENCY = 5000;

#endif // _GENERIC_PROTOCOL_CONSTANTS_HPP